"""What each parameter checks and how its score is worked out, in plain words.

The same for every audit -- no site names, no measured values, no symbols. The pop-up shows
it above the audit's own numbers (see working.py). Keep each entry in step with the handler.
"""

# parameter id -> (what it checks, how the score is worked out)
SIMPLE_LOGIC: dict[str, tuple[str, str]] = {
    # Technical
    "TECH-01": ("Whether the site's robots.txt file lets the main AI crawlers (such as GPTBot and ClaudeBot) read the site.",
                "The score is the share of the five AI crawlers that are allowed in."),
    "TECH-02": ("Whether the site's firewall or CDN actually serves pages to AI crawlers, or blocks them.",
                "The homepage is requested as each of five AI crawlers. The score is the share that get the real page instead of a block or an empty page."),
    "TECH-03": ("Whether the site has an llms.txt file (a short guide for AI tools) and whether it is useful and up to date.",
                "No file scores zero. A file starts at 40, and gains points for having real content, for links that work, and for showing a date."),
    "TECH-04": ("Whether cookie banners, pop-ups or a login wall hide the main content of the homepage.",
                "Full marks with no pop-ups or login wall. A partial score if pop-ups exist but the page still has plenty of text, and a low score otherwise."),
    "TECH-05": ("Whether the site has an XML sitemap, whether its links work, and whether it lists the pages that really exist.",
                "Points for having a sitemap, more for sitemap links that work, and more for how many of the crawled pages it lists. No sitemap scores zero."),
    "TECH-06": ("Whether the site's internal links work, without broken pages or long redirect chains.",
                "The score is the share of internal links that work, with a few points taken off for each long redirect chain."),
    "TECH-07": ("How fast the site's pages respond and how heavy they are to download.",
                "Response time and page size are each rated from good to poor. Response time counts for more than page size in the final score."),
    "TECH-08": ("Whether the site uses HTTPS and is set up to display properly on mobile phones.",
                "Half the score for HTTPS and half for a mobile viewport setting. The score is held back if the page forces a fixed desktop width."),
    "TECH-09": ("Whether the main content is in the page's HTML, or only appears after JavaScript runs (which many AI tools cannot run).",
                "The page is compared before and after JavaScript. The more content that only appears after JavaScript, the lower the score."),
    "TECH-10": ("Whether each page has one main heading (H1) and a sensible order of sub-headings.",
                "Each page starts at full marks and loses points for a missing or repeated H1 and for skipped heading levels. The score is the average across pages."),
    "TECH-11": ("Whether the content is broken into short sections under headings that an AI assistant could quote on their own.",
                "The score is the share of sections that could be lifted and quoted without needing the rest of the page."),
    "TECH-12": ("Whether the site uses real tables and lists (not images of them), which AI tools can read.",
                "Full marks when the site has plenty of tables and lists, a partial score with a few, and a low score with almost none."),
    "TECH-13": ("Whether pages have enough real text compared with code, and enough depth of content.",
                "Each page is rated on its text-to-code balance and on its length against a target. The score is the average across pages."),
    "TECH-14": ("Whether images have useful descriptions (alt text) and videos have transcripts.",
                "Mostly based on the share of images with useful alt text, and partly on the share of videos with a transcript."),
    "TECH-15": ("Whether pages show when they were published or last updated.",
                "Every site starts with a base score, and gains more the higher the share of pages that show a date."),
    "TECH-16": ("Whether the homepage describes the company in structured data: name, website, logo, social profiles and contact details.",
                "Points for each of the four main company details found, plus a bonus when an address or contact detail is also given."),
    "TECH-17": ("Whether each type of page (article, service, about page and so on) carries the matching structured data.",
                "The score is the share of pages whose structured data matches what kind of page they are."),
    "TECH-18": ("Whether articles and pages name their authors in a way machines can read.",
                "A low score with no author information, a good score when authors are marked up, and a high score when authors also have a job title."),
    "TECH-19": ("Whether the structured data (JSON-LD) on the site is written correctly and can be read without errors.",
                "The score is the share of structured-data blocks that are valid."),
    "TECH-20": ("Whether each page points to the correct main version of itself (a canonical tag) without long redirects.",
                "The score is the share of pages with a correct canonical tag and no long redirect chain."),
    "TECH-21": ("For sites serving several countries or languages, whether the language tags (hreflang) are set up correctly.",
                "The score is the share of language tags that are complete. Sites serving one market are not scored."),
    "TECH-22": ("Whether every page has a title and description, and whether they are unique and a sensible length.",
                "Points for having titles and descriptions, for them being unique, and for them being a good length."),
    # On-Page
    "ON-01": ("Whether page headings are phrased as the questions buyers actually ask.",
              "The higher the share of headings that are real buyer questions, the higher the score."),
    "ON-02": ("Whether each question heading is followed by a direct, clear answer of a useful length.",
              "Each answer is rated on its length, with the best score for a short, complete answer. The score is the average of all answers."),
    "ON-03": ("Whether the site clearly defines the key terms and services it talks about.",
              "The score is the share of the site's key concepts that are clearly defined somewhere on the site."),
    "ON-04": ("Whether each page opens with something concrete instead of generic filler.",
              "The score is the share of pages whose opening lines get straight to the point."),
    "ON-05": ("Whether service pages include an FAQ section.",
              "The score is the share of service pages that have an FAQ section or FAQ structured data."),
    "ON-06": ("Whether FAQ content is both visible on the page and marked up as structured data.",
               "Each FAQ page earns half for the visible FAQ and half for the FAQ markup. The score is the average; a site with no FAQs gets a low fixed score."),
    "ON-07": ("Whether pages that compare options (pricing, features, alternatives) include a comparison table.",
              "The score is the share of comparison-style pages that include a real table."),
    "ON-08": ("Whether the site uses useful lists and step-by-step points, not just menus.",
              "The score is the share of content lists that are genuinely useful to a reader."),
    "ON-09": ("Whether pages are written naturally, without stuffing the same keyword over and over.",
              "The score is high when no single word dominates the page, and lower when one word is repeated too often."),
    "ON-10": ("Whether service pages cover what a buyer needs: the problem, approach, scope, results, audience, pricing, proof and next step.",
              "Each service page is rated on how many of these eight points it covers. The score is the average across pages."),
    "ON-11": ("Whether key pages include original facts and figures from the company.",
              "The score is the share of key pages that carry an original statistic."),
    "ON-12": ("Whether content is credited to real, named people with a stated role.",
              "The score rises with how many bylines name a real person and give their role, with a minimum score."),
    "ON-13": ("Whether case studies and proof pages name real clients, give measurable results and describe the work done.",
              "Each page earns points for a named client, a measured result and deployment details, with a bonus when client and result appear together. The score is the average."),
    "ON-14": ("Whether statistics and claims on the site say where they come from.",
              "The score is the share of statistical claims that point to a source a reader could check."),
    "ON-15": ("Whether pages show a published or last-updated date to readers.",
              "Every site starts with half marks, and gains more the higher the share of pages that show a date."),
    "ON-16": ("Whether the site has content for every stage of a buyer's journey, from first learning about the topic to deciding to buy.",
              "The score is how many of the six buying stages have content, out of six."),
    "ON-17": ("Whether the site has pages that compare its offering with alternatives.",
              "A high score with several genuine comparison pages, a middle score with one or two, and a low score with none."),
    "ON-18": ("Whether several pages compete for the same topic with nearly identical titles.",
              "The higher the share of pages with no competing duplicate, the higher the score."),
    "ON-19": ("Whether pages are thin (very little text) or near-copies of other pages.",
              "The higher the share of pages that are neither thin nor duplicated, the higher the score."),
    "ON-20": ("Whether pages name the brand, what it offers and where it operates, all together.",
              "The score is the share of pages that mention the brand, a service category and a location together."),
    # Off-Page
    "OFF-01": ("Whether the company has an entry on Wikidata and an article on Wikipedia.",
               "A yes or no check. Full marks when the company is on both Wikidata and Wikipedia, and zero when either one is missing."),
    "OFF-02": ("Whether the company has the entity record a Google Knowledge Panel is built from, with consistent details.",
               "Zero when the company has no entity record. With one, a base score plus extra points when it has a description and carries the brand name."),
    "OFF-03": ("Whether the company has profiles on LinkedIn, Crunchbase, Bloomberg and ZoomInfo, showing the same name and locations as its own website.",
               "Most of the score comes from how many of the four profiles exist. The rest comes from the profiles showing the same company name and office locations as the site."),
    "OFF-04": ("Whether the site states certifications, accreditations or partner tiers such as ISO, CMMI or gold partner status.",
               "A middle score when certification claims are found and a lower score when none are. The score stays capped because the claims are not verified with the issuer."),
    "OFF-05": ("Whether the company is listed on the main review sites (G2, Clutch, Gartner and TrustRadius) under the right category.",
               "Most of the score comes from how many of the four review sites list the company. The rest is added when those listings place it in the category it uses itself."),
    "OFF-06": ("How many reviews the company has on the main review sites, and how recent the latest one is.",
               "Points for the number of reviews found, plus extra points when the newest review is from the last year, and fewer when it is from the last two years."),
    "OFF-07": ("Whether the company is discussed on Reddit, Quora and industry forums.",
               "The more community discussions that mention the company, the higher the score."),
    "OFF-08": ("Whether the company appears on 'best' and 'top' lists for its category.",
               "Full marks when the company appears in the search results for the best companies in its category. Otherwise the score rises with the number of best-of lists that name it."),
    "OFF-09": ("Whether analysts, directories and the trade press cover the company, and describe it accurately.",
               "A high score when coverage describes the company accurately, a middle score when it does not, and a low score when there is none."),
}


def logic_for(parameter_id: str) -> dict | None:
    entry = SIMPLE_LOGIC.get(parameter_id)
    return {"checks": entry[0], "scoring": entry[1]} if entry else None
